name: CI

on:
  push:
    branches:
      - master
      - feat/*
      - fix/*
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [14, 16, 18]
        include:
          - os: macos-latest
            node_version: 16
          - os: windows-latest
            node_version: 16
      fail-fast: false
    name: "Build: node-${{ matrix.node_version }}, ${{ matrix.os }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.15.1

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: "pnpm"

      - name: Install deps
        run: pnpm install --registry=https://registry.npmmirror.com/
      
      - name: Test with coverage
        run: pnpm coverage

      - uses: codecov/codecov-action@v3
        with:
          commit_parent: ${{ github.event.pull_request.head.sha }}

      - name: Build
        run: pnpm build
      